function grav = gravity(a2,a3,g,m2,m3,pl2_1,pl2_2,pl3_1,pl3_2,q2,q3)
%GRAVITY
%    GRAV = GRAVITY(A2,A3,G,M2,M3,PL2_1,PL2_2,PL3_1,PL3_2,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    22-Feb-2023 10:30:21

t2 = cos(q2);
t3 = cos(q3);
t4 = sin(q2);
t5 = sin(q3);
t6 = a2.*t2;
t7 = t2.*t3;
t8 = t2.*t5;
t9 = t3.*t4;
t10 = t4.*t5;
t11 = a3.*t7;
t12 = a3.*t10;
t13 = -t10;
t15 = t8+t9;
t14 = -t12;
t16 = pl3_2.*t15;
t17 = t7+t13;
t18 = pl3_1.*t17;
t19 = -t16;
grav = [0.0;g.*m2.*(t6+pl2_1.*t2-pl2_2.*t4)+g.*m3.*(t6+t11+t14+t18+t19);g.*m3.*(t11+t14+t18+t19)];
