function grav = gravity(a2,a3,g,m2,m3,pl2_1,pl2_2,pl3_1,pl3_2,q2,q3)
%GRAVITY
%    GRAV = GRAVITY(A2,A3,G,M2,M3,PL2_1,PL2_2,PL3_1,PL3_2,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    20-Feb-2023 18:21:17

t2 = cos(q2);
t3 = q2+q3;
t4 = a2.*t2;
t5 = cos(t3);
t6 = sin(t3);
t7 = a3.*t5;
t8 = pl3_1.*t5;
t9 = pl3_2.*t6;
t10 = -t9;
grav = [0.0;g.*m3.*(t4+t7+t8+t10)+g.*m2.*(t4+pl2_1.*t2-pl2_2.*sin(q2));g.*m3.*(t7+t8+t10)];
